openapi: 3.0.0
info:
  title: API do Artigo
  version: 1.0.6
  description: Descrição da minha API

paths:
  /GetExams:
    get:
      summary: Retorna os exames do banco de dados
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  uf:
                    type: string
                    example: CE
                  period:
                    type: string
                    example: 202403
                  score:
                    type: number
                    example: 100
  /RegisterExam:
    post:
      summary: Insere exames no banco de dados
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  category_id:
                    type: integer
                    example: 1
                  uf:
                    type: string
                    example: CE
                  period:
                    type: integer
                    example: 202403
                  amount_error:
                    type: integer
                    example: 7
                  amount_right:
                    type: integer
                    example: 3
              example:
                - category_id: 1
                  uf: CE
                  period: 202403
                  amount_error: 7
                  amount_right: 3
                - category_id: 2
                  uf: CE
                  period: 202403
                  amount_error: 5
                  amount_right: 5
                - category_id: 4
                  uf: CE
                  period: 202403
                  amount_error: 1
                  amount_right: 9
                - category_id: 4
                  uf: RJ
                  period: 202403
                  amount_error: 1
                  amount_right: 9
      responses:
        '200':
          description: Dados coletados com sucesso. Gerando planilha no servidor
  /GetCategoryData:
    post:
      summary: Retorna dados da categoria.
      parameters:
        - in: query
          name: periodo
          schema:
            type: string
          description: Período no formato "YYYYMM".
      responses:
        '200':
          description: OK
      requestBody:
        required: false
        content:
          application/json:
            example:
              periodo: "202402"
    