openapi: 3.0.0
info:
  title: API do Artigo
  version: 1.0.2
  description: Descrição da minha API

paths:
  /GetExams:
    get:
      summary: Retorna os exames do banco de dados
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  uf:
                    type: string
                    example: CE
                  period:
                    type: string
                    example: 202403
                  score:
                    type: number
                    example: 100
  /RegisterExam: 
    post:                                  
      summary: Insere exames no banco de dados
      requestBody:                         
        required: true
        content:
          application/json:
            schema:
              type: array
              properties:
                  uf:
                    type: string
                    example: CE
                  period:
                    type: string
                    example: 202403
                  score:
                    type: number
                    example: 100
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  nome:
                    type: string
                    example: Jorge
                  estado:
                    type: string
                    example: Rj
                  nota:
                    type: number
                    example: 100
  